using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Media.Effects;
using System.Windows.Media;
using System.Windows;

namespace BallAndStickTest
{

    //------------------------------------------------------------------------------
    // <auto-generated>
    //     此代码由工具生成。
    //     运行时版本:4.0.30319.239
    //
    //     对此文件的更改可能会导致不正确的行为，并且如果
    //     重新生成代码，这些更改将会丢失。
    // </auto-generated>
    //------------------------------------------------------------------------------

    public class UseGpu : ShaderEffect
    {
        public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(UseGpu), 0);
        public UseGpu()
        {
            PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri("shaders/fucktest.ps", UriKind.Relative);
            this.PixelShader = pixelShader;

            this.UpdateShaderValue(InputProperty);
            //this.Changed += FU;
            pixelShader.Changed += FU;
        }

        void FU(Object sender, EventArgs e)
        {
            int i = 0;
        }

        public void UpdateGpu()
        {
            UpdateShaderValue(InputProperty);
        }

        public Brush Input
        {
            get
            {
                return ((Brush)(this.GetValue(InputProperty)));
            }
            set
            {
                this.SetValue(InputProperty, value);
            }
        }
    }
    //class UseGpu : ShaderEffect
    //{
    //    private static PixelShader ps = new PixelShader();

    //    public UseGpu()
    //    {
    //        ps.UriSource = new Uri("shaders/fucktest.ps", UriKind.Relative);
    //        PixelShader = ps;
    //    }

    //    public void UpdateGpu()
    //    {
    //        UpdateShaderValue(InputProperty);
    //    }

    //    #region Input

    //    public Brush Input
    //    {
    //        get { return (Brush)GetValue(InputProperty); }
    //        set { SetValue(InputProperty, value); }
    //    }

    //    public static readonly DependencyProperty InputProperty =
    //        ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(UseGpu), 0);


    //    #endregion
    //}
}
